### ISSUE TITLE
Plotter performance

### ISSUE THREAD

**Issue by gribeill** [BBN-Q/Auspex#436]
New plotter is considerably (2x...) slower and crashes often with the following trace:

```python
Traceback (most recent call last):
  File "./auspex-plot-client.py", line 482, in data_signal_received
    self.canvas_by_name[plot_name].update_figure(data)
  File "./auspex-plot-client.py", line 249, in update_figure
    self.draw()
  File "/home/qlab/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 391, in draw
    super().draw()
  File "/home/qlab/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 485, in draw
    self.update()
```

**Comment by gribeill** [comment]
#437 appears to fix segfaults caused by a missing MDI window status bar. 
Appears that a lot of the slowdown is caused by `constrained_layout=True`?
